apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  resources:
    requests: {}
  serviceAccountAnnotations: {}
  tolerations:
  - operator: Exists
  volumeMounts:
  - mountPath: pbpewewtlo
    name: kvbcgsvxxa
    readOnly: true
