apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  labels:
    app.kubernetes.io/name: fluent-bit
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: ghcr.io/xlab-uiuc/fluent-bit:v2.1.7
  securityContext:
    fsGroup: 0
    runAsGroup: 0
    runAsUser: 0
  tolerations:
  - effect: NoExecute
    key: node-role.kubernetes.io/control-plane
    operator: Exists
    tolerationSeconds: 3600
