apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  labels:
    app.kubernetes.io/name: fluent-bit
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: ghcr.io/xlab-uiuc/fluent-bit:v2.1.7
  resources:
    requests: {}
  serviceAccountAnnotations:
    ACTOKEY: ACTOKEY
  tolerations:
  - operator: Exists
