apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  readinessProbe:
    initialDelaySeconds: 10
    tcpSocket:
      port: 8500
  tolerations:
  - operator: Exists
