apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  schedulerName: 1ld.y6uhuih.w.rftix5rq.w.d
  tolerations:
  - operator: Exists
