apiVersion: anvil.dev/v1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-cluster
        topologyKey: kubernetes.io/hostname
  image: rabbitmq:3.11.10-management
  persistence:
    storage: 10Gi
    storageClassName: null
  rabbitmqConfig:
    additionalConfig: 'log.console.level = debug

      '
  replicas: 3
