apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  hostNetwork: true
  image: kubesphere/fluent-bit:v2.1.7
  resources:
    requests:
      ACTOKEY: .53m
  tolerations:
  - operator: Exists
