apiVersion: anvil.dev/v1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq
spec:
  image: rabbitmq:3.11.10-management
  persistence:
    storage: 10Gi
    storageClassName: null
  rabbitmqConfig:
    additionalConfig: 'log.console.level = debug

      '
  replicas: 3
  tolerations:
  - effect: NoExecute
    key: test-key
    operator: Equal
    tolerationSeconds: 3600
    value: test-value
  - effect: NoExecute
    key: node-role.kubernetes.io/control-plane
    operator: Exists
    tolerationSeconds: 3600
