apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq-system
spec:
  affinity: null
  image: ghcr.io/xlab-uiuc/rabbitmq:3.11.10-management
  persistence:
    storage: 10Gi
    storageClassName: null
  rabbitmq:
    additionalConfig: 'log.console.level = debug

      '
  replicas: 5
