apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq-system
spec:
  image: ghcr.io/xlab-uiuc/rabbitmq:3.11.10-management
  persistence:
    storage: 10Gi
    storageClassName: null
  rabbitmq:
    additionalConfig: 'log.console.level = debug

      '
  replicas: 3
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  tolerations:
  - effect: NoExecute
    key: test-key
    operator: Equal
    tolerationSeconds: 3600
    value: test-value
  - effect: NoExecute
    key: node-role.kubernetes.io/control-plane
    operator: Exists
    tolerationSeconds: 3600
