apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  tolerations:
  - operator: Exists
  volumeMounts:
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: true
    subPath: ACTOKEY
    subPathExpr: ACTOKEY
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: false
    subPath: ACTOKEY
    subPathExpr: ACTOKEY
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: true
    subPath: null
    subPathExpr: ACTOKEY
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: false
    subPath: ACTOKEY
    subPathExpr: ACTOKEY
