apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  initContainers:
  - name: x
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 1000m
        memory: 1000m
        xolfixlrgg: 1000m
  tolerations:
  - operator: Exists
