apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  readinessProbe:
    httpGet:
      port: 8500
    initialDelaySeconds: 10
  tolerations:
  - operator: Exists
