apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  initContainers:
  - args:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    command:
    - ACTOKEY
    env:
    - name: ACTOKEY
      value: null
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: ACTOKEY
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: null
          optional: false
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: ACTOKEY
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: null
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: ACTOKEY
          resource: ACTOKEY
        secretKeyRef: null
    envFrom:
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: null
      secretRef:
        name: ACTOKEY
        optional: true
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart:
        exec:
          command: []
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
      preStop:
        exec:
          command: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket: null
    livenessProbe:
      exec:
        command: []
      failureThreshold: 1
      grpc:
        port: 2
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: null
      periodSeconds: 2
      successThreshold: 0
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 1
      timeoutSeconds: null
    name: t
    ports: []
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 2
      grpc:
        port: 3
        service: null
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 4
      periodSeconds: 5
      successThreshold: 2
      tcpSocket:
        host: null
        port: ACTOKEY
      terminationGracePeriodSeconds: 4
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        drop:
        - ACTOKEY
        - ACTOKEY
      privileged: false
      procMount: ACTOKEY
      readOnlyRootFilesystem: false
      runAsGroup: 2
      runAsNonRoot: false
      runAsUser: 3
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: ACTOKEY
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: ACTOKEY
        gmsaCredentialSpecName: ACTOKEY
        hostProcess: false
        runAsUserName: ACTOKEY
    startupProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 0
      grpc:
        port: 2
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders: null
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 4
      periodSeconds: 2
      successThreshold: 0
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 2
      timeoutSeconds: 4
    stdin: false
    stdinOnce: false
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: true
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts: []
    workingDir: ACTOKEY
  - args:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    command:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: ACTOKEY
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    envFrom: []
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart:
        exec:
          command:
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
      preStop:
        exec: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
    livenessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 1
      grpc:
        port: 5
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: null
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: null
      periodSeconds: null
      successThreshold: 0
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 2
      timeoutSeconds: 5
    name: p
    ports:
    - containerPort: 3
      hostIP: ACTOKEY
      hostPort: 5
      name: ACTOKEY
      protocol: ACTOKEY
    - containerPort: 2
      hostIP: ACTOKEY
      hostPort: 1
      name: ACTOKEY
      protocol: ACTOKEY
    - containerPort: 4
      hostIP: ACTOKEY
      hostPort: 4
      name: ACTOKEY
      protocol: null
    readinessProbe:
      exec: null
      failureThreshold: 5
      grpc:
        port: 1
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 3
      periodSeconds: 1
      successThreshold: 4
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 3
      timeoutSeconds: 4
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: null
      capabilities:
        add:
        - ACTOKEY
        drop:
        - ACTOKEY
      privileged: null
      procMount: ACTOKEY
      readOnlyRootFilesystem: true
      runAsGroup: null
      runAsNonRoot: true
      runAsUser: 3
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: ACTOKEY
      seccompProfile:
        localhostProfile: null
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: ACTOKEY
        gmsaCredentialSpecName: ACTOKEY
        hostProcess: true
        runAsUserName: ACTOKEY
    startupProbe:
      exec: null
      failureThreshold: 2
      grpc:
        port: 0
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: null
      periodSeconds: null
      successThreshold: null
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 2
      timeoutSeconds: 2
    stdin: true
    stdinOnce: false
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: false
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts:
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: null
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: true
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: true
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    workingDir: ACTOKEY
  - args:
    - ACTOKEY
    command:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    env: []
    envFrom: []
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle: null
    livenessProbe: null
    name: n6zewety
    ports:
    - containerPort: 0
      hostIP: ACTOKEY
      hostPort: 1
      name: ACTOKEY
      protocol: ACTOKEY
    - containerPort: 3
      hostIP: ACTOKEY
      hostPort: 5
      name: ACTOKEY
      protocol: ACTOKEY
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 4
      grpc:
        port: 0
        service: ACTOKEY
      httpGet:
        host: null
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        path: null
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 5
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 2
      timeoutSeconds: 2
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add: null
        drop: []
      privileged: true
      procMount: ACTOKEY
      readOnlyRootFilesystem: false
      runAsGroup: 3
      runAsNonRoot: false
      runAsUser: 5
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: ACTOKEY
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions: null
    startupProbe:
      exec:
        command:
        - ACTOKEY
      failureThreshold: 1
      grpc: null
      httpGet:
        host: ACTOKEY
        httpHeaders: null
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 4
      periodSeconds: 3
      successThreshold: 4
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 0
      timeoutSeconds: 2
    stdin: true
    stdinOnce: false
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: true
    volumeDevices: []
    volumeMounts:
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: true
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    workingDir: ACTOKEY
  tolerations:
  - operator: Exists
