apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  imagePullSecrets:
  - name: ''
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  tolerations:
  - operator: Exists
