apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  dnsPolicy: p.e.0mu0g.csqxqxii.b.l.u20lycv5x3.zgkrj87yphf.t0-4m7
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  tolerations:
  - operator: Exists
