apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  priorityClassName: p4a9-fncax.d9.puso.2
  tolerations:
  - operator: Exists
