apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: ghcr.io/xlab-uiuc/fluent-bit:v2.1.7
  livenessProbe:
    grpc:
      port: 8500
    initialDelaySeconds: 10
  tolerations: []
