apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  initContainers:
  - args:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    command:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef: null
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef: null
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    envFrom:
    - configMapRef:
        name: ACTOKEY
        optional: false
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    - configMapRef:
        name: ACTOKEY
        optional: false
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    - configMapRef:
        name: ACTOKEY
        optional: false
      prefix: ACTOKEY
      secretRef: null
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart: null
      preStop:
        exec:
          command: []
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: null
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
    livenessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 5
      grpc:
        port: 4
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders: []
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 3
      periodSeconds: 4
      successThreshold: 3
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 3
      timeoutSeconds: 0
    name: k2r4
    ports:
    - containerPort: 5
      hostIP: ACTOKEY
      hostPort: 3
      name: null
      protocol: ACTOKEY
    - containerPort: 2
      hostIP: ACTOKEY
      hostPort: 4
      name: ACTOKEY
      protocol: ACTOKEY
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 3
      grpc:
        port: 2
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 5
      periodSeconds: 3
      successThreshold: 5
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 3
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - ACTOKEY
        - ACTOKEY
        drop: []
      privileged: false
      procMount: ACTOKEY
      readOnlyRootFilesystem: true
      runAsGroup: 2
      runAsNonRoot: false
      runAsUser: 3
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: null
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: ACTOKEY
        gmsaCredentialSpecName: ACTOKEY
        hostProcess: false
        runAsUserName: ACTOKEY
    startupProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 2
      grpc: null
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: null
      periodSeconds: 2
      successThreshold: null
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 4
      timeoutSeconds: 1
    stdin: true
    stdinOnce: true
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: false
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts: []
    workingDir: null
  resources:
    limits: {}
  tolerations:
  - operator: Exists
