apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  disableLogVolumes: true
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  resources:
    claims:
    - name: ''
  tolerations:
  - operator: Exists
