apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  ports:
  - containerPort: 1
    hostIP: ACTOKEY
    hostPort: 1
    name: ACTOKEY
    protocol: ACTOKEY
  tolerations:
  - operator: Exists
