apiVersion: anvil.dev/v1
kind: FluentBit
metadata:
  name: test-cluster
spec:
  fluentBitConfigName: fluent-bit-config
  image: kubesphere/fluent-bit:v2.1.7
  resources:
    requests:
      ACTOKEY: .00323e.78634
  tolerations: []
